name: CI/CD

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build and test data-search service
      run: |
        cd data-search
        npm install
        npm run build
        npm test

    - name: Build and test statistics-manager service
      run: |
        cd statistics-manager
        npm install
        npm run build
        npm test
